---
openapi: 3.2.0

info:
  title: Workastra Desk API
  version: '1'
  description: API documentation for Workastra Desk application.

servers:
  - url: /api/v1

tags:
  - name: Health
    description: Health check endpoints

paths:
  /health/live:
    get:
      summary: Liveness Probe
      description: Endpoint to check if the application is running.
      tags: [Health]
      responses:
        default:
          description: Application is live.
          content:
            text/plain:
              schema:
                type: string
                example: OK

  /health/ready:
    get:
      summary: Readiness Probe
      description: Endpoint to check if the application is ready to handle requests.
      tags: [Health]
      responses:
        '200':
          description: Application is ready.
          content:
            application/json:
              schema:
                type: object
                required: [code, data]
                additionalProperties: false
                properties:
                  code:
                    type: string
                    example: S0200
                  data:
                    type: object
                    required: [env]
                    additionalProperties: false
                    properties:
                      env:
                        type: boolean
                        example: true
        '500':
          description: Application is not ready.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: E0500
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                        example: unhealthy
                      details:
                        type: string
                        example: Database connection failed
